### ISSUE TITLE
AttributeError line 507, in __repair_chunk

### ISSUE THREAD

**Issue by anarchy9388** [anarchy9388/chunky_monkey#14]
`Traceback (most recent call last):
  File "chunky_monkey.py", line 1001, in <module>
    chunky_monkey_inst.main()
  File "chunky_monkey.py", line 926, in main
    self.do_fix(dry_run=dry_run, non_parity=self.args['non_parity'])
  File "chunky_monkey.py", line 704, in do_fix
    self.__repair_chunk(chunk_info, issue_type, dry_run)
  File "chunky_monkey.py", line 507, in __repair_chunk
    ecEncodePaddingToCapacity = chunk_info['body'].get('copies', {}).get('ecEncodePaddingToCapacity')
AttributeError: 'list' object has no attribute 'get'
admin@fmcecs082n2:/tmp/chunky_monkey>`

**Comment by anarchy9388** [comment]
```
Traceback (most recent call last):
  File "/tmp/mike/chunky_monkey-1.0.dev5/chunky_monkey.py", line 969, in <module>
    chunky_monkey_inst.main()
  File "/tmp/mike/chunky_monkey-1.0.dev5/chunky_monkey.py", line 894, in main
    self.do_fix(dry_run=dry_run, non_parity=self.args['non_parity'])
  File "/tmp/mike/chunky_monkey-1.0.dev5/chunky_monkey.py", line 658, in do_fix
    self.__repair_chunk(chunk_info, issue_type, dry_run)
  File "/tmp/mike/chunky_monkey-1.0.dev5/chunky_monkey.py", line 478, in __repair_chunk
    ecEncodePaddingToCapacity = chunk_info['body'].get('copies', {}).get('ecEncodePaddingToCapacity')
AttributeError: 'list' object has no attribute 'get'
```

**Comment by anarchy9388** [comment]
```
==============================   2a064bb1-d15e-4463-a009-4550b0de9766   ==============================
2 of 907 chunks

Getting chunk info for chunkId 2a064bb1-d15e-4463-a009-4550b0de9766..DONE
Analyzing chunk info..DONE
Legacy parity chunk possibly found, attempting to repair chunk..
Checking for segments with zero checksum..DONE
Dumping segments to confirm chunk version..{'locationType': 'STORAGE_SERVER', 'endOffset': '132781905', 'ssLocation': {'status': 'HEALTHY', 'partitionId': '6d3f2883-ae8a-4b77-9e42-0e87930d432a', 'statusSn': '-1', 'filename': '0578', 'offset': '5256856000', 'ssId': '10.73.33.25'}, 'offset': '0'}
locationType
Traceback (most recent call last):
  File "/tmp/mike/chunky_monkey-1.0.dev5/chunky_monkey.py", line 1248, in <module>
    chunky_monkey_inst.main()
  File "/tmp/mike/chunky_monkey-1.0.dev5/chunky_monkey.py", line 1157, in main
    self.do_fix(dry_run=dry_run, non_parity=self.args['non_parity'])
  File "/tmp/mike/chunky_monkey-1.0.dev5/chunky_monkey.py", line 713, in do_fix
    self.__repair_chunk(chunk_info, issue_type, dry_run)
  File "/tmp/mike/chunky_monkey-1.0.dev5/chunky_monkey.py", line 570, in __repair_chunk
    sequence = segment['sequence']
TypeError: string indices must be integers, not str
```

**Comment by anarchy9388** [comment]
```
status: SEALED
dataType: REPO
type: PARITY
repGroup: "urn:storageos:ReplicationGroupInfo:33955cef-0b29-4eb3-80f3-4237a1f6928b:global"
primary: "urn:storageos:VirtualDataCenterData:bc05b984-a0d3-4471-bd91-8f43a2022875"
encodedChunks: "93a121bc-e14e-4962-ae28-c98c0b518cb7"
encodedChunks: "56f0b22e-9493-4a16-9353-fcfc1f0e8219"
copies {
  isEc: false
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.25"
      partitionId: "6d3f2883-ae8a-4b77-9e42-0e87930d432a"
      filename: "0578"
      offset: 5256856000
      status: HEALTHY
      statusSn: -1
    }
    offset: 0
    endOffset: 132781905
  }
}
copies {
  isEc: false
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.12"
      partitionId: "8e8c2588-0c9d-4c0a-9c04-791aeb2f345f"
      filename: "0628"
      offset: 4429181408
      status: HEALTHY
      statusSn: -1
    }
    offset: 0
    endOffset: 132781905
  }
}
copies {
  isEc: false
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.27"
      partitionId: "22acfee1-94ef-4172-bb34-1e2e2d81a4f3"
      filename: "0002"
      offset: 7650403200
      status: BAD
      statusSn: 14214138
    }
    offset: 0
    endOffset: 132781905
  }
}
capacity: 134217600
sealedLength: 132781905
isEcEncoded: false
sequenceNumber: 0
minNotSealedSequenceNumber: 0
checksum: "2989337875"
```

**Comment by anarchy9388** [comment]
```
169.254.1.4 2019-07-23T18:28:04,507 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-096] DEBUG  RecoverUtil.java (line 1405) chunk:2a064bb1-d15e-4463-a009-4550b0de9766, nBad:1
169.254.1.4 2019-07-23T18:28:04,507 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-096] DEBUG  RecoverUtil.java (line 1416) chunk:2a064bb1-d15e-4463-a009-4550b0de9766, priority:7
169.254.1.4 2019-07-23T18:28:04,507 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-096] DEBUG  RecoverUtil.java (line 1647) chunk:2a064bb1-d15e-4463-a009-4550b0de9766, priority:7
169.254.1.4 2019-07-23T18:28:04,507 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-096] DEBUG  RepairChunkEvent.java (line 44) start handleRepair, chunkId: 2a064bb1-d15e-4463-a009-4550b0de9766
169.254.1.4 2019-07-23T18:28:04,507 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-096] DEBUG  RecoverChunkChecker.java (line 1211) add allocate block callable for chunk:2a064bb1-d15e-4463-a009-4550b0de9766
169.254.1.4 2019-07-23T18:28:04,507 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-096] DEBUG  RepairChunkTaskScanner.java (line 221) run postCallable after handleRepair, chunk:2a064bb1-d15e-4463-a009-4550b0de9766, callable size:1
169.254.1.4 2019-07-23T18:28:04,508 [TaskScheduler-ChunkManager-ParallelExecutor-116] DEBUG  RecoverAllocateNormalBlockCallable.java (line 57) Start allocating blocks for chunk:2a064bb1-d15e-4463-a009-4550b0de9766, new normal copies number:1, existedSs:{10.73.33.12=SelectedSsInfo: [selectedNum:1, partitions:[]], 10.73.33.25=SelectedSsInfo: [selectedNum:1, partitions:[]]}
169.254.1.4 2019-07-23T18:28:04,508 [TaskScheduler-ChunkManager-ParallelExecutor-116] ERROR  RecoverAllocateBlockCallable.java (line 143) Hit exception while allocating blocks for recovery, chunk id: 2a064bb1-d15e-4463-a009-4550b0de9766, exception:
java.lang.IllegalArgumentException: range size: 132781905 should be multiple of chunk alignment size.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:93)
        at com.emc.storageos.data.chunkmanager.utils.Allocator.getNormalBlockAllocationHintList(Allocator.java:816)
        at com.emc.storageos.data.chunkmanager.statemachine.impl.postcallable.RecoverAllocateNormalBlockCallable.allocateBlocks(RecoverAllocateNormalBlockCallable.java:78)
        at com.emc.storageos.data.chunkmanager.statemachine.impl.postcallable.RecoverAllocateBlockCallable.call(RecoverAllocateBlockCallable.java:132)
        at com.emc.storageos.data.chunkmanager.statemachine.impl.postcallable.RecoverAllocateBlockCallable.call(RecoverAllocateBlockCallable.java:36)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
169.254.1.4 2019-07-23T18:38:08,534 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-041]  INFO  RepairChunkTaskScanner.java (line 87) received RepairChunkTaskEntry schemaType CM_TASK type REPAIR order 7 chunkId 2a064bb1-d15e-4463-a009-4550b0de9766
169.254.1.4 2019-07-23T18:38:08,534 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-041] DEBUG  ChunkTable.java (line 182) get chunk 2a064bb1-d15e-4463-a009-4550b0de9766 from urn:storageos:OwnershipInfo:5fd9876a-845e-4559-bb8d-861710dd3965__CT_1_128_1:
169.254.1.4 2019-07-23T18:38:08,535 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-041] DEBUG  ChunkTable.java (line 219) query chunkId:2a064bb1-d15e-4463-a009-4550b0de9766, get:status: SEALED
dataType: REPO
type: PARITY
repGroup: "urn:storageos:ReplicationGroupInfo:33955cef-0b29-4eb3-80f3-4237a1f6928b:global"
primary: "urn:storageos:VirtualDataCenterData:bc05b984-a0d3-4471-bd91-8f43a2022875"
encodedChunks: "93a121bc-e14e-4962-ae28-c98c0b518cb7"
encodedChunks: "56f0b22e-9493-4a16-9353-fcfc1f0e8219"
copies {
  isEc: false
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.25"
      partitionId: "6d3f2883-ae8a-4b77-9e42-0e87930d432a"
      filename: "0578"
      offset: 5256856000
      status: HEALTHY
      statusSn: -1
    }
    offset: 0
    endOffset: 132781905
  }
}
copies {
  isEc: false
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.12"
      partitionId: "8e8c2588-0c9d-4c0a-9c04-791aeb2f345f"
      filename: "0628"
      offset: 4429181408
      status: HEALTHY
      statusSn: -1
    }
    offset: 0
    endOffset: 132781905
  }
}
copies {
  isEc: false
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.27"
      partitionId: "22acfee1-94ef-4172-bb34-1e2e2d81a4f3"
      filename: "0002"
      offset: 7650403200
      status: BAD
      statusSn: 14214138
    }
    offset: 0
    endOffset: 132781905
  }
}
capacity: 134217600
sealedLength: 132781905
isEcEncoded: false
sequenceNumber: 0
minNotSealedSequenceNumber: 0
checksum: "2989337875"
169.254.1.4 2019-07-23T18:38:08,536 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-041] DEBUG  RecoverUtil.java (line 1405) chunk:2a064bb1-d15e-4463-a009-4550b0de9766, nBad:1
169.254.1.4 2019-07-23T18:38:08,536 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-041] DEBUG  RecoverUtil.java (line 1416) chunk:2a064bb1-d15e-4463-a009-4550b0de9766, priority:7
169.254.1.4 2019-07-23T18:38:08,536 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-041] DEBUG  RecoverUtil.java (line 1647) chunk:2a064bb1-d15e-4463-a009-4550b0de9766, priority:7
169.254.1.4 2019-07-23T18:38:08,536 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-041] DEBUG  RepairChunkEvent.java (line 44) start handleRepair, chunkId: 2a064bb1-d15e-4463-a009-4550b0de9766
169.254.1.4 2019-07-23T18:38:08,536 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-041] DEBUG  RecoverChunkChecker.java (line 1211) add allocate block callable for chunk:2a064bb1-d15e-4463-a009-4550b0de9766
169.254.1.4 2019-07-23T18:38:08,536 [TaskScheduler-ChunkManager-DEFAULT_BACKGROUND_OPERATION-ScheduledExecutor-041] DEBUG  RepairChunkTaskScanner.java (line 221) run postCallable after handleRepair, chunk:2a064bb1-d15e-4463-a009-4550b0de9766, callable size:1
169.254.1.4 2019-07-23T18:38:08,536 [TaskScheduler-ChunkManager-ParallelExecutor-056] DEBUG  RecoverAllocateNormalBlockCallable.java (line 57) Start allocating blocks for chunk:2a064bb1-d15e-4463-a009-4550b0de9766, new normal copies number:1, existedSs:{10.73.33.12=SelectedSsInfo: [selectedNum:1, partitions:[]], 10.73.33.25=SelectedSsInfo: [selectedNum:1, partitions:[]]}
169.254.1.4 2019-07-23T18:38:08,536 [TaskScheduler-ChunkManager-ParallelExecutor-056] ERROR  RecoverAllocateBlockCallable.java (line 143) Hit exception while allocating blocks for recovery, chunk id: 2a064bb1-d15e-4463-a009-4550b0de9766, exception:
java.lang.IllegalArgumentException: range size: 132781905 should be multiple of chunk alignment size.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:93)
        at com.emc.storageos.data.chunkmanager.utils.Allocator.getNormalBlockAllocationHintList(Allocator.java:816)
        at com.emc.storageos.data.chunkmanager.statemachine.impl.postcallable.RecoverAllocateNormalBlockCallable.allocateBlocks(RecoverAllocateNormalBlockCallable.java:78)
        at com.emc.storageos.data.chunkmanager.statemachine.impl.postcallable.RecoverAllocateBlockCallable.call(RecoverAllocateBlockCallable.java:132)
        at com.emc.storageos.data.chunkmanager.statemachine.impl.postcallable.RecoverAllocateBlockCallable.call(RecoverAllocateBlockCallable.java:36)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

admin@FWDCPACSECS02:~>
```

**Comment by anarchy9388** [comment]
```
admin@FWDCPACSECS02:~> svc_dt search CT/1 -s CM_TASK -t REPAIR -p "2a064bb1-d15e-4463-a009-4550b0de9766"

svc_dt v1.0.20 (svc_tools v1.5.4)                 Started 2019-07-23 18:53:02

Searching for:
  DT Type/Level:       CT/1
  Schema:              CM_TASK

  Additional key (header) filters:
    type:              REPAIR
    (plaintext match): 2a064bb1-d15e-4463-a009-4550b0de9766

schemaType CM_TASK type REPAIR order 7 chunkId 2a064bb1-d15e-4463-a009-4550b0de9766
dataToRecover: 132781905


admin@FWDCPACSECS02:~> curl -v -X PUT "http://$ip:9101/cm/recover/addEcTask/$cos/1/2a064bb1-d15e-4463-a009-4550b0de9766"
* Hostname was NOT found in DNS cache
*   Trying 10.73.33.76...
* Connected to 10.73.33.76 (10.73.33.76) port 9101 (#0)
> PUT /cm/recover/addEcTask/urn:storageos:VirtualArray:5fd9876a-845e-4559-bb8d-861710dd3965/1/2a064bb1-d15e-4463-a009-4550b0de9766 HTTP/1.1
> User-Agent: curl/7.37.0
> Host: 10.73.33.76:9101
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 23 Jul 2019 18:57:07 GMT
< Content-Length: 13
<
add ec task
* Connection #0 to host 10.73.33.76 left intact
admin@FWDCPACSECS02:~> svc_dt search CT/1 -s CM_TASK -t EC -p "2a064bb1-d15e-4463-a009-4550b0de9766"

svc_dt v1.0.20 (svc_tools v1.5.4)                 Started 2019-07-23 18:57:16

Searching for:
  DT Type/Level:       CT/1
  Schema:              CM_TASK

  Additional key (header) filters:
    type:              EC
    (plaintext match): 2a064bb1-d15e-4463-a009-4550b0de9766


No matches found.


admin@FWDCPACSECS02:~> svc_chunk info -id 2a064bb1-d15e-4463-a009-4550b0de9766 -raw
svc_chunk v2.1.1 (svc_tools v1.5.4)                 Started 2019-07-23 18:57:35

Fetching chunk info for 1 chunks
status: SEALED
dataType: REPO
type: PARITY
repGroup: "urn:storageos:ReplicationGroupInfo:33955cef-0b29-4eb3-80f3-4237a1f6928b:global"
primary: "urn:storageos:VirtualDataCenterData:bc05b984-a0d3-4471-bd91-8f43a2022875"
encodedChunks: "93a121bc-e14e-4962-ae28-c98c0b518cb7"
encodedChunks: "56f0b22e-9493-4a16-9353-fcfc1f0e8219"
copies {
  isEc: true
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.15"
      partitionId: "d38c2a95-a1c8-4d5d-89bc-050fed492d7b"
      filename: "0237"
      offset: 9764330560
      status: HEALTHY
      statusSn: -1
      tag: 1563908230480
      partitionIdUuid {
        highBytes: 15243605660895038813
        lowBytes: 9924813244781374843
      }
    }
    checksum: "3427081643"
    offset: 0
    endOffset: 11184800
    sequence: 0
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.12"
      partitionId: "6888c5af-8a9c-4dae-b414-828d0b2d1f65"
      filename: "0635"
      offset: 6822728032
      status: HEALTHY
      statusSn: -1
      tag: 1563908230433
      partitionIdUuid {
        highBytes: 7532487734512602542
        lowBytes: 12976139968650747749
      }
    }
    checksum: "718810521"
    offset: 11184800
    endOffset: 22369600
    sequence: 1
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.17"
      partitionId: "0ec165c4-60fd-4636-8417-3426fc8db142"
      filename: "0668"
      offset: 10133428928
      status: HEALTHY
      statusSn: -1
      tag: 1563908230442
      partitionIdUuid {
        highBytes: 1063242881151354422
        lowBytes: 9518133679521378626
      }
    }
    checksum: "2670633459"
    offset: 22369600
    endOffset: 33554400
    sequence: 2
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.11"
      partitionId: "8bec0525-cce2-4091-a566-e4a81ee79794"
      filename: "0270"
      offset: 6341781600
      status: HEALTHY
      statusSn: -1
      tag: 1563908230499
      partitionIdUuid {
        highBytes: 10082439325685006481
        lowBytes: 11918464874606729108
      }
    }
    checksum: "3412637624"
    offset: 33554400
    endOffset: 44739200
    sequence: 3
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.25"
      partitionId: "2110561c-7f7f-4f61-bcb2-6459739bb1ac"
      filename: "0266"
      offset: 6341781792
      status: HEALTHY
      statusSn: -1
      tag: 1563908230473
      partitionIdUuid {
        highBytes: 2382498883277115233
        lowBytes: 13597040560339399084
      }
    }
    checksum: "2823112873"
    offset: 44739200
    endOffset: 55924000
    sequence: 4
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.24"
      partitionId: "6ad16879-60e3-4a60-88de-9fc5718a8530"
      filename: "0584"
      offset: 8433339200
      status: HEALTHY
      statusSn: -1
      tag: 1563908230453
      partitionIdUuid {
        highBytes: 7697048108678728288
        lowBytes: 9862495904350242096
      }
    }
    checksum: "2065861384"
    offset: 55924000
    endOffset: 67108800
    sequence: 5
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.14"
      partitionId: "56837795-d3b4-437d-b3c1-a55148fe12d9"
      filename: "0100"
      offset: 7728696800
      status: HEALTHY
      statusSn: -1
      tag: 1563908230443
      partitionIdUuid {
        highBytes: 6233957794596537213
        lowBytes: 12952815771829801689
      }
    }
    checksum: "2236301310"
    offset: 67108800
    endOffset: 78293600
    sequence: 6
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.75"
      partitionId: "0b342d6a-b54e-4b02-95f3-500d22080459"
      filename: "0628"
      offset: 4429180800
      status: HEALTHY
      statusSn: -1
      tag: 1563908230471
      partitionIdUuid {
        highBytes: 807320169537751810
        lowBytes: 10805067948327699545
      }
    }
    checksum: "360607863"
    offset: 78293600
    endOffset: 89478400
    sequence: 7
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.78"
      partitionId: "0b738c6a-1329-414e-943e-f0eb476c3a7f"
      filename: "0121"
      offset: 5111453696
      status: HEALTHY
      statusSn: -1
      tag: 1563908230481
      partitionIdUuid {
        highBytes: 825157543954825550
        lowBytes: 10682240259475651199
      }
    }
    checksum: "3644375376"
    offset: 89478400
    endOffset: 100663200
    sequence: 8
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.22"
      partitionId: "c9ebaac7-8fe2-4ad0-ba60-cdc60dc51c26"
      filename: "0093"
      offset: 883599232
      status: HEALTHY
      statusSn: -1
      tag: 1563908230449
      partitionIdUuid {
        highBytes: 14549910795239705296
        lowBytes: 13429960339337059366
      }
    }
    checksum: "501126780"
    offset: 100663200
    endOffset: 111848000
    sequence: 9
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.23"
      partitionId: "a124b6a7-a3e0-4b36-a325-60972d190f12"
      filename: "0455"
      offset: 8690589600
      status: HEALTHY
      statusSn: -1
      tag: 1563908230473
      partitionIdUuid {
        highBytes: 11611606570393160502
        lowBytes: 11755908604733493010
      }
    }
    checksum: "1159843233"
    offset: 111848000
    endOffset: 123032800
    sequence: 10
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.13"
      partitionId: "105325e2-2053-4e45-a07d-afeb0ce2c0b2"
      filename: "0577"
      offset: 5782541664
      status: HEALTHY
      statusSn: -1
      tag: 1563908230473
      partitionIdUuid {
        highBytes: 1176325580808998469
        lowBytes: 11564592842225664178
      }
    }
    checksum: "895095449"
    offset: 123032800
    endOffset: 134217600
    sequence: 11
    virtualOffset: 132781905
    virtualEndOffset: 134217600
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.77"
      partitionId: "cc059c5c-9d31-4d9a-829a-99c3f0c2de15"
      filename: "0491"
      offset: 279620000
      status: HEALTHY
      statusSn: -1
      tag: 1563908230446
      partitionIdUuid {
        highBytes: 14701328480209030554
        lowBytes: 9411003438181047829
      }
    }
    checksum: "2108100480"
    offset: 134217600
    endOffset: 145402400
    sequence: 12
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.16"
      partitionId: "00ec3450-ce12-4c7e-b19d-74db2d8d8651"
      filename: "0306"
      offset: 1152034464
      status: HEALTHY
      statusSn: -1
      tag: 1563908230464
      partitionIdUuid {
        highBytes: 66485616163048574
        lowBytes: 12798514200767727185
      }
    }
    checksum: "2978980710"
    offset: 145402400
    endOffset: 156587200
    sequence: 13
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.27"
      partitionId: "0600a4a0-5eeb-4a5e-b394-fbfa82a335ee"
      filename: "0211"
      offset: 4306148032
      status: HEALTHY
      statusSn: -1
      tag: 1563908230471
      partitionIdUuid {
        highBytes: 432526572921768542
        lowBytes: 12940244682694407662
      }
    }
    checksum: "1851206997"
    offset: 156587200
    endOffset: 167772000
    sequence: 14
  }
  segments {
    locationType: STORAGE_SERVER
    ssLocation {
      ssId: "10.73.33.76"
      partitionId: "f44c7920-c792-45ba-9a4a-bf97ad4988dd"
      filename: "0083"
      offset: 1375730400
      status: HEALTHY
      statusSn: -1
      tag: 1563908230450
      partitionIdUuid {
        highBytes: 17603578225178592698
        lowBytes: 11117909288285735133
      }
    }
    checksum: "640524393"
    offset: 167772000
    endOffset: 178956800
    sequence: 15
  }
  ecStatus: COMPLETED
  ecCodeScheme {
    numberOfDataBlocks: 12
    numberOfCodeBlocks: 4
  }
  ecEncodePaddingToCapacity: true
  ecBlockSize: 11184800
  isEcEncodedByClient: false
}
capacity: 134217600
sealedLength: 132781905
isEcEncoded: true
sequenceNumber: 0
minNotSealedSequenceNumber: 0
checksum: "2989337875"




admin@FWDCPACSECS02:~>
```

**Comment by anarchy9388** [comment]
Opened  #20 for handling new scenario.

Closing this issue for handling the AttributeError so script doesn't  stop #19
